### PR TITLE
Check current tag before re-rendering

### LINKED ISSUE #50: Infinite loop when observing 'args' in a computed property that returns an array that is iterated over by {{#each}}
```javascript
import Component, {tracked} from "@glimmer/component";
export default class MyComponent extends Component {
    @tracked('args') get arrayTest() {
        console.log('bye');
        return [1, 2];
    }
};
```

```handlebars
<div>
    {{#each arrayTest key='@index' as |num|}}
         {{num}}
    {{/each}}
</div>
```

With the above component, and template, the computed property gets recomputed in an infinite loop.  You'll see `bye` in the console forever.

If you remove `{{num}}` from the inside of the `{{#each}}`, the infinite loop does not happen.

### PR DESCRIPTION
**Pull request by chadhietala**
I'm not sure what is going on with the tests here, but this is likely what needs to be done. Should close #50 and #43

### CODE REVIEW

**Comment by chadhietala** [comment]
This is likely not correct.

**Comment by tomdale** [comment]
This is unnecessary because the only thing that should be scheduling rendering should also bump the current revision. If there are places that are scheduling a rerender without bumping the tag, we should discuss that because it's a violation of the current assumptions.

**Comment by chadhietala** [comment]
Well there is still something going wrong. An idempotent set causes the everything to get re-rendered.
screen shot 2017-04-09 at 12 07 15 pm

**Comment by tomdale** [comment]
I believe that is working as intended. The diffing happens on reads, not writes. The set would cause `CURRENT_REVISION` to be bumped. @chancancode @wycats Please let me know if I have this wrong.

**Pull request closed without merging**
